---
title: "IntrotoR"
output: html_document
date: '2023-09-08'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Function to pull sequence data from NCBI using NCBI accession 
```{r}
getncbiseq <- function(accession)
{
require("seqinr") # this function requires the SeqinR R package
# first find which ACNUC database the accession is stored in:
dbs <- c("genbank","refseq","refseqViruses","bacterial")
numdbs <- length(dbs)
for (i in 1:numdbs)
{
db <- dbs[i]
choosebank(db)
# check if the sequence is in ACNUC database 'db':
resquery <- try(query(".tmpquery", paste("AC=", accession)), silent = TRUE)
if (!(inherits(resquery, "try-error")))
{
queryname <- "query2"
thequery <- paste("AC=", accession, sep="")
query2 <- query(queryname, thequery)
# see if a sequence was retrieved:
seq <- getSequence(query2$req[[1]])
closebank()
return(seq)
}
closebank()
}
print(paste("ERROR: accession",accession,"was not found"))
}
```

Test to pull in sequence data using function and display first 50 nucleotides of sequence.
```{r}
dengueseq <- getncbiseq("NC_001477")
dengueseq[1:50]
```
